{
  "id": 2719,
  "name": "Retry on fail except for known error",
  "totalViews": 656,
  "purchaseUrl": null,
  "user": {
    "id": 91699,
    "name": "Mario",
    "username": "octionic",
    "bio": "Workflow Optimization Expert | Software Architect. Use my link to book an initial consultation for custom built workflows using n8n.",
    "verified": true,
    "links": "[\"https://octionic.com\"]",
    "avatar": "https://gravatar.com/avatar/48bf351cec848d87566d8cc78c9a783ec4807408366648de04cfe955d7a5ba21?r=pg&d=retro&size=200"
  },
  "description": "Purpose\n\nThis workflow snippet allows for advanced error catching during retry attempts.\n\nThere are cases, where you want to check if an item exists first, so you can determine the following actions. Some API’s do not support an endpoint (e.g. Todoist: completed tasks) to do so, which is why you would work with the error branch, only that this does not work well in combination with the retry functionality.\n\nHow it works\n\nInstead of the builtin retry function of a Node a custom loop is used, to get more granular control in between the iterations\nIf the main executed node fails, the error can be filtered for an expected error, which can trigger a separate action\nThe retries only happen, if an unexpected error happened\nThe workflow only stops, if the defined amount of retries exceeded\n\nSetup\n\nCopy the nodes into your existing workflow\nReplace the “Replace me” placeholder with the Node you want to apply the retry logic on\nFollow the sticky notes for more instructions and optional settings",
  "createdAt": "2025-01-12T13:17:18.184Z",
  "nodes": []
}